name: Manual News Fetch

on:
  workflow_dispatch:

jobs:
  fetch-news-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # এখানে ২০ থেকে ২২ করে দিলাম

    - name: Install dependencies
      run: npm install

    - name: Run Fetch Script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: node fetch-news.js
